[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "ninja",
    "cmake>=3.12",
    "conan>=2.0.0",
    "scikit-build-core",
    "skbuild-conan",
]
build-backend = "setuptools.build_meta"
