name: pip

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-13, ubuntu-latest]
        python-version: ["3.7", "3.11"]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add requirements
      run: python -m pip install --upgrade pip wheel setuptools conan
    - name: Conan detect profile
      run: conan profile detect
    - name: Build and install
      run: pip install --verbose .[test]
    # TODO
    #- name: Test
    #  run: python -m pytest
