name: wheels

on:
  pull_request:
  push:
    branches:
    - main
  release:
    types:
    - published

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Build SDist
      run: pipx run build --sdist
    - name: Check metadata
      run: pipx run twine check dist/*
    - uses: actions/upload-artifact@v4
      with:
        name: cibw-sdist
        path: dist/*.tar.gz

  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-13]
    steps:
    - uses: actions/checkout@v4
    - uses: pypa/cibuildwheel@v2.17
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.15
        CIBW_ARCHS_MACOS: auto universal2
        CIBW_SKIP: "*-win32 *-manylinux_i686"
        CIBW_BEFORE_BUILD: "pip install conan && conan remote add --index 0 odr https://artifactory.opendocument.app/artifactory/api/conan/conan"
        CIBW_BUILD_VERBOSITY: 1
    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}
        path: wheelhouse/*.whl

  upload_all:
    name: Upload if release
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-24.04
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - uses: actions/download-artifact@v4
      with:
        pattern: cibw-*
        path: dist
        merge-multiple: true
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.pypi_password }}
